const PDFDocument = require("pdfkit");

function formatMoney(value) {
  return `EUR ${Number(value || 0).toFixed(2)}`;
}

function formatDate(value) {
  if (!value) return "-";
  return new Date(value).toLocaleString("it-IT");
}

function generateReservationPdf(data) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: "A4",
        margin: 50
      });

      const chunks = [];

      doc.on("data", (chunk) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));

      const unitPrice = Number(data.price || 0);
      const quantity = Number(data.quantity || 0);
      const total = unitPrice * quantity;

      doc
        .fontSize(22)
        .text("SportManiaTravel", { align: "center" });

      doc
        .moveDown(0.3)
        .fontSize(14)
        .text("Reservation Confirmation", { align: "center" });

      doc.moveDown(2);

      doc
        .fontSize(11)
        .text(`Confirmation Date: ${formatDate(new Date())}`);

      doc.moveDown(1);

      doc
        .fontSize(16)
        .text("Partner Details", { underline: true });

      doc.moveDown(0.5);

      doc.fontSize(11);
      doc.text(`Company: ${data.company_name || "-"}`);
      doc.text(`Contact: ${data.contact_name || "-"}`);
      doc.text(`Email: ${data.email || "-"}`);

      doc.moveDown(1.3);

      doc
        .fontSize(16)
        .text("Event Details", { underline: true });

      doc.moveDown(0.5);

      doc.fontSize(11);
      doc.text(`Event: ${data.event_name || "-"}`);
      doc.text(`Event Date: ${formatDate(data.event_date)}`);
      doc.text(`Venue: ${data.venue || "-"}`);
      doc.text(`City: ${data.city || "-"}`);
      doc.text(`Country: ${data.country || "-"}`);
      doc.text(`Macro Area: ${data.event_type || "-"}`);
      doc.text(`Subcategory: ${data.event_subcategory || "-"}`);

      doc.moveDown(1.3);

      doc
        .fontSize(16)
        .text("Ticket Details", { underline: true });

      doc.moveDown(0.5);

      doc.fontSize(11);
      doc.text(`Supplier Ticket ID: ${data.supplier_ticket_id || "-"}`);
      doc.text(`Category: ${data.category || "-"}`);
      doc.text(`Block: ${data.block || "-"}`);
      doc.text(`Row: ${data.row_name || "-"}`);
      doc.text(`Seats: ${data.seat_from || "-"} - ${data.seat_to || "-"}`);
      doc.text(`Quantity: ${quantity}`);
      doc.text(`Unit Price: ${formatMoney(unitPrice)}`);
      doc.text(`Total: ${formatMoney(total)}`);

      doc.moveDown(1.3);

      doc
        .fontSize(16)
        .text("Reservation Details", { underline: true });

      doc.moveDown(0.5);

      doc.fontSize(11);
      doc.text(`Request ID: ${data.request_id || "-"}`);
      doc.text(`Reservation Code: ${data.reservation_code || "-"}`);
      doc.text(`Status: confirmed`);
      doc.text(`Approved At: ${formatDate(data.approved_at)}`);

      if (data.notes) {
        doc.moveDown(1);
        doc.text(`Notes: ${data.notes}`);
      }

      doc.moveDown(2);

      doc
        .fontSize(9)
        .fillColor("#64748b")
        .text(
          "This document is an automatic confirmation generated by SportManiaTravel Inventory Supplier Platform.",
          { align: "center" }
        );

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}

module.exports = generateReservationPdf;